lyceum/about/urls.py
from django.urls import path
from . import views

app_name = 'about'  

urlpatterns = [
    path('', views.description, name='description'),
]

lyceum/catalog/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'catalog'

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('items/', views.item_list, name='item_list'),
    path('items/<int:pk>/', views.item_detail, name='item_detail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyceum/feedback/urls.py
from django.urls import path
from .views import feedback

app_name = 'feedback'

urlpatterns = [
    path('', feedback, name='feedback'),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from catalog.views import main_page


urlpatterns = [
    path("", main_page, name="main_page"),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyceum/templates/includes/footer.html
<footer class="text-center mt-5 py-3 border-top">
    <p>© черемша</p>
</footer>

lyceum/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-success bg-light">
  <div class="container">
    <a class="navbar-brand" href="{% url 'main_page' %}">
      <img src="{% static 'images/logo.png' %}" alt="Logo" width="50">
    </a>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'main_page' %}">На главную</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.path == '/about/' %}active{% endif %}" href="{% url 'about:description' %}">О проекте</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if '/catalog/' in request.path %}active{% endif %}" href="{% url 'catalog:item_list' %}">Список товаров</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if '/feedback/' in request.path %}active{% endif %}" href="{% url 'feedback:feedback' %}">Обратная связь</a>
      </li>

      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if '/users/profile/' in request.path %}active{% endif %}" href="{% url 'profile' %}">Профиль</a>
        </li>
        <li class="nav-item">
          <form action="{% url 'logout' %}" method="post" style="display:inline;">
            {% csrf_token %}
            <button class="nav-link btn btn-link" type="submit" style="padding: 0; margin-left: 10px;">Выйти</button>
          </form>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link {% if '/users/login/' in request.path %}active{% endif %}" href="{% url 'login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if '/users/signup/' in request.path %}active{% endif %}" href="{% url 'signup' %}">Регистрация</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

lyceum/templates/includes/item_card.html
{% load static %}

<div class="card h-100">
  {% if item.main_image %}
    <img src="{{ item.main_image.url }}" class="card-img-top" alt="{{ item.name }}">
  {% else %}
    <img src="{% static 'images/photo.png' %}" class="card-img-top" alt="Заглушка">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ item.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ item.category.name }}</h6>
    <p class="card-text">{{ item.text|truncatewords:10 }}</p>
    <p>
      {% for tag in item.tags.all %}
        <span class="badge bg-secondary">{{ tag.name }}</span>
      {% endfor %}
    </p>
    <a href="{% url 'catalog:item_detail' item.pk %}" class="btn btn-primary">Подробнее</a>
  </div>
</div>