lyceum/about/urls.py
from django.urls import path
from . import views

app_name = 'about'  

urlpatterns = [
    path('', views.description, name='description'),
]

lyceum/homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path("", views.home, name="home"),
    path('echo/', views.echo_view, name='echo'),
    path('echo/submit/', views.echo_submit, name='echo_submit'),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from catalog.views import main_page


urlpatterns = [
    path("", main_page, name="main_page"),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path('feedback/', include('feedback.urls', namespace='feedback')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lyceum/homepage/forms.py
from django import forms

class EchoForm(forms.Form):
    text = forms.CharField(
        label="Введите текст",
        widget=forms.Textarea(attrs={"rows": 3, "class": "form-control"}),
        help_text="Этот текст отобразится на следующей странице"
    )

lyceum/homepage/views.py
from django.shortcuts import render
from catalog.models import Item
from django.http import HttpResponseNotAllowed, HttpResponse
from .forms import EchoForm

def home(request):
    items = Item.objects.filter(is_published=True).select_related('category').prefetch_related('tags')
    return render(request, 'homepage/home.html', {'items': items})


def echo_view(request):
    return render(request, 'homepage/echo.html', {'form': EchoForm()})


def echo_submit(request):
    if request.method != 'POST':
        return HttpResponseNotAllowed(['POST'])

    form = EchoForm(request.POST)
    if form.is_valid():
        text = form.cleaned_data['text']
        return HttpResponse(text, content_type='text/plain')
    return HttpResponse("Неверные данные", status=400)

lyceum/templates/homepage/echo.html
{% extends 'base.html' %}

{% block title %}Echo{% endblock %}

{% block content %}
  <h1>Форма Echo</h1>
  <form method="post" action="{% url 'homepage:echo_submit' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Отправить</button>
  </form>
{% endblock %}

lyceum/templates/homepage/home.html
{% extends 'base.html' %}

{% block content %}
<h1 class="mb-4 text-primary">Проверка главной страницы</h1>

<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for item in items %}
    <div class="col">
      {% include 'includes/item_card.html' %}
    </div>
  {% endfor %}
</div>
{% endblock %}